dist: xenial
language: elixir
elixir: 1.9
otp_release: 22.0
services:
  - docker
env:
  global:
    - MYSQL_SOCKET_DIR=/var/run/mysqld
    - MYSQL_UNIX_PORT=/var/run/mysqld/mysqld.sock
  matrix:
    - DB=mysql:8.0
    - DB=mysql:5.7
    - DB=mysql:5.6
    - DB=mariadb:10.3
matrix:
  include:
    - otp_release: 18.3.4.11
      elixir: 1.4.5
    - otp_release: 18.3.4.11
      elixir: 1.5.3
    - otp_release: 19.3.6.13
      elixir: 1.6.6
    - otp_release: 19.3.6.13
      elixir: 1.7.4
    - otp_release: 20.3.8.26
      elixir: 1.8.2
    - otp_release: 20.3.8.26
      elixir: 1.9.4
    - otp_release: 21.3.8.16
      elixir: 1.10.4
    - otp_release: 23.0.2
      elixir: 1.10.4
    - env: DB=none
      script:
        - mix compile --warnings-as-errors
        - mix format --check-formatted
script:
  - sudo service mysql stop
  - scripts/ci.sh
