name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 18.3.4.11
            elixir: 1.4.5
          - otp: 18.3.4.11
            elixir: 1.5.3
          - otp: 19.3.6.13
            elixir: 1.6.6
          - otp: 19.3.6.13
            elixir: 1.7.4
          - otp: 20.3.8.26
            elixir: 1.8.2
          - otp: 20.3.8.26
            elixir: 1.9.4
          - otp: 21.3.8.16
            elixir: 1.10.4
          - otp: 23.0.2
            elixir: 1.10.4
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-elixir@v1.3.0
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
    - run: mix test

  check_formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - otp: 23.0.2
            elixir: 1.10.4
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Check formatted for Elixir ${{matrix.elixir}}
        run: mix format --check-formatted

  compile_without_warnings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - otp: 23.0.2
            elixir: 1.10.4
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
      - name: Compile without warnings on Elixir ${{matrix.elixir}}
        run: mix compile --warnings-as-errors
